"""The Evolving Hive-Mind Trader — a simulation, with the straitjacket attached.

    market.py    the tape, and fills that cost what fills cost
    memory.py    the Obsidian brain: outcomes, filed by regime
    scouts.py    five fresh minds that fact-check themselves
    council.py   confidence-weighted votes, and a conviction floor
    evolver.py   the genome, and the only code allowed to change it
    engine.py    the book, the arithmetic, the narration
    lock.py      the four phases a genome must clear before real money

Run it:

    python -m hive_mind                 # the narrated simulation
    python -m hive_mind --lock          # the full walk-forward pipeline
    python -m hive_mind --show-hallucination   # perfect fills vs real ones

It borrows from the village rather than re-deriving: ``src/money.py`` for the
Decimal arithmetic, ``src/trading/indicators.py`` for the performance
statistics, ``src/trading/models.py`` for the bar, the fill and the
quantisers, and ``src/trading/execution/paper.py`` for what a fill costs. It
shares none of the village *itself* — no database, no ledger, no firms, no
brokerage, no human gate. Nothing in `src/` imports anything from here.

This is a flight simulator. Nothing in it connects to a broker, and the market
it trades is generated by ``market.py``, not observed. See README.md.
"""

from __future__ import annotations

from .council import Decision, VillageCouncil
from .engine import GodBrokerEngine, MutationRefused, Result, backtest
from .evolver import BASE_GENOME, Evolver, Genome, SIZING_GENES, STRATEGY_GENES
from .lock import LockConfig, LockReport, Permit, Phase, WalkForwardLock, strategy_fingerprint
from .market import MarketFeed, PerfectVenue, SCENARIOS, Venue, WindowFeed
from .memory import ObsidianMemory, Recall
from .scouts import Proposal, ScoutAI

__all__ = [
    "BASE_GENOME",
    "Decision",
    "Evolver",
    "Genome",
    "GodBrokerEngine",
    "LockConfig",
    "LockReport",
    "MarketFeed",
    "MutationRefused",
    "ObsidianMemory",
    "Permit",
    "PerfectVenue",
    "Phase",
    "Proposal",
    "Recall",
    "Result",
    "SCENARIOS",
    "SIZING_GENES",
    "STRATEGY_GENES",
    "ScoutAI",
    "Venue",
    "VillageCouncil",
    "WalkForwardLock",
    "WindowFeed",
    "backtest",
    "strategy_fingerprint",
]
