"""Write bots/vol_rotation/ASTRAL.md from the ten bots' own parameters.

Astral (heyastral.ai) builds a strategy from a plain-English description, so
each bot becomes one self-contained prompt with every number spelled out.
Generated rather than hand-written, so the prompts cannot drift from the code
they describe:

    python scripts/vol_rotation_astral.py
"""

from __future__ import annotations

import ast
import importlib.util
import sys
from dataclasses import asdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.trading import vol_rotation  # noqa: E402

BOTS = REPO / "bots" / "vol_rotation"
OUT = BOTS / "ASTRAL.md"


def _module(path: Path):
    """Import one of the bots. They are this repository's own files."""
    spec = importlib.util.spec_from_file_location(f"vol_rotation_bot_{path.stem}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _title(path: Path) -> str:
    doc = ast.get_docstring(ast.parse(path.read_text())) or ""
    return doc.splitlines()[0].split(":", 1)[-1].strip().rstrip(".")


def _about(path: Path) -> str:
    doc = ast.get_docstring(ast.parse(path.read_text())) or ""
    return " ".join(doc.split("\n\n")[1].split())


def prompt(title: str, universe: list, p: vol_rotation.Params) -> str:
    crypto = p.bars_per_year == vol_rotation.CRYPTO_15M_BARS_PER_YEAR
    session = ("24/7, every 15-minute bar" if crypto
               else "regular US market hours only (9:30-16:00 ET), 15-minute bars")
    held = "the single best-ranked ticker" if p.hold == 1 else f"the top {p.hold} ranked tickers"
    tickers = ", ".join(universe)
    return f"""Build a volatility rotation strategy called "Vol Rotation: {title}".

Universe: {tickers}. Long only, no leverage, no shorting. Timeframe: {session}.
Evaluate on each bar close.

Indicators, per ticker:
- Short volatility = standard deviation of 1-bar log returns over the last {p.vol_window} bars.
- Long volatility = standard deviation of 1-bar log returns over the last {p.long_vol_window} bars.
- Vol ratio = short volatility / long volatility.
- Annualised volatility = short volatility x sqrt({p.bars_per_year}).
- Momentum = ln(close / close {p.mom_window} bars ago).
- Score = momentum / (short volatility x sqrt({p.mom_window})).
- Relative volume (RVOL) = this bar's volume / average volume of the previous {p.volume_window - 1} bars.
- VWAP = volume-weighted average close over the last {p.volume_window} bars.
- Up bar = close > open. Down bar = close < open.

Ranking and rotation:
- Eligible = score > {p.min_score} AND vol ratio <= {p.max_vol_ratio}.
- Rank eligible tickers by score, adding {p.switch_margin} to the score of any ticker currently held (so a challenger must clearly beat a holding to replace it).
- Targets = {held}.

Position sizing:
- Full position per ticker = {p.max_weight:.0%} of equity x min(1, {p.target_vol:.0%} / annualised volatility).
- A full position is split into {p.tranches} equal tranches.

Scaling in (targets only), on a bar where ALL are true: up bar, close > VWAP, RVOL >= {p.rvol_in}:
- Buy 1 tranche, or 2 tranches if RVOL >= {p.rvol_surge}, never exceeding the full position.
- A quiet up bar (RVOL < {p.rvol_in}) adds nothing.

Scaling out:
- Exit the whole position immediately if score < 0 or vol ratio > {p.max_vol_ratio}.
- A held ticker that is no longer a target: sell 1 tranche per bar; 2 tranches if RVOL >= {p.rvol_out}; everything if RVOL >= {p.rvol_surge} on a down bar.
- A held target that prints a down bar below VWAP with RVOL >= {p.rvol_out} (distribution): sell 1 tranche.
- If a holding is worth more than 110% of its full position (volatility rose), trim it back to the full position.
- If a sale would leave less than a quarter of a tranche, sell the whole position.

Process sells before buys on each bar. Backtest with commissions and slippage on."""


def main() -> int:
    sections = []
    for path in sorted(BOTS.glob("*.py")):
        bot = _module(path)
        universe = bot.UNIVERSE
        params = vol_rotation.Params.from_mapping(bot.PARAMS)
        title = _title(path)
        sections.append(
            f"## {path.stem[:2]}. {title}\n\n{_about(path)}\n\n"
            f"Repo version: `bots/vol_rotation/{path.name}`\n\n"
            "```text\n" + prompt(title, universe, params) + "\n```\n"
        )
    header = """# The ten bots, as Astral prompts

Paste one block at a time into Astral's strategy builder (heyastral.ai). Each
block is self-contained and describes exactly what the matching file in this
folder does, with every number the code uses, so a backtest there and a
backtest here are tests of the same strategy.

Generated by `python scripts/vol_rotation_astral.py` from the bots' own
parameters. Change a bot, rerun the script, and this file follows. Do not edit
it by hand.

**Check what Astral built before you trust its backtest.** It writes the
strategy from these words, and an AI builder can quietly change a rule, for
example by dropping the volume gate or reading "tranche" loosely. Its editor
shows the rules it wrote, so check them against the block you pasted.

"""
    OUT.write_text(header + "\n".join(sections))
    print(f"wrote {OUT.relative_to(REPO)} ({len(sections)} strategies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
